apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: stefanhans/webserver:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: webserver-service
  labels:
    app: webserver
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 8080
    #targetPort: 80
  type: LoadBalancer
