apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: update-job
spec:
  template:
    metadata:
      name: update-job
    spec:
      containers:
      - name: update-job
        image: update-out-cluster
        command: ["/app"]
        args: [""]
      # Do not restart containers after they exit
      restartPolicy: Never