apiVersion: experimental
kind: DynamicYaml
name: my-app
variables:
  - deployment: ["version"]
  - service: ["nodePort"]
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: webserver
        image: stefanhans/webserver:{{VERSION}1.0.1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 8080
    nodePort: {{NODEPORT}30001
  type: LoadBalancer
