apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-hello-world-deployment
  labels:
    app: go-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
      - name: go-hello-world
        image: stefanhans/go-hello-world:latest
