apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webserver-prod-deployment
  labels:
    app: webserver
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
      env: production
  template:
    metadata:
      labels:
        app: webserver
        env: production
    spec:
      containers:
      - name: webserver
        image: stefanhans/webserver:1.0.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: webserver-service
  labels:
    app: webserver
    env: production
spec:
  selector:
    app: webserver
    env: production
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
